### GET - profile data
GET http://localhost:3000/api/profile HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiSmFuMiIsImxhc3ROYW1lIjoiS293YTNsc2tpIiwiZW1haWwiOiJ1c2VyMTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMDgkVE91L09vSURjcWFWMEQ1dThQUjRBT1V5bGpEaDhMS1pqdnFwNE0zcDloLnlUa0lzMTV2bFciLCJjb25maXJtZWQiOmZhbHNlLCJpYXQiOjE2ODUzOTQwMzIsImV4cCI6MTY4NTM5NDA2Mn0.Bke-mYJjrwV6QmelhnP8gD5g2n6wVrWGJpDlcWza-kU