### GET - profile data
GET http://localhost:3000/api/profile HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZmlyc3ROYW1lIjoiYmFydGVrIiwibGFzdE5hbWUiOiJrb3oiLCJlbWFpbCI6InVzZXJAdXNlci5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCRoUXVGQlNObVlhNEdFckZOMU5iUjQuTE1JQ1NMR3Z6YXpKN2dST1hBWWNaZmRsYWtLOWVHcSIsInBmcCI6IkQ6XFxCYXJ0ZWtcXFN6a2_FgmFcXMWBxIVjem5vxZvEh1xcMFNURUZBTkNaWUtcXGluc3RhcHBcXGFwcFxccGZwXFxkZWZhdWx0LmpwZyIsImNvbmZpcm1lZCI6dHJ1ZSwiaWF0IjoxNjg2NDk0MTI2LCJleHAiOjE2ODY0OTc3MjZ9.RY1wWDAvpt530cmk3XK4UOlAf2faY4SE0JgTN8iIJ24

### PATCH - profile data
PATCH http://localhost:3000/api/profile HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZmlyc3ROYW1lIjoiQmFydGVrIiwibGFzdE5hbWUiOiJrb3oiLCJlbWFpbCI6InVzZXJAdXNlci5jb20iLCJwYXNzd29yZCI6IiQyYSQwOCRrZGxFYnAuMU9sWWV6ZFNGazNJRWUudEV5eDdZbHR4MDZWTFRxMVhkdy9DQUdaMWlMZHg2TyIsInBmcCI6IkQ6XFxCYXJ0ZWtcXFN6a2_FgmFcXMWBxIVjem5vxZvEh1xcMFNURUZBTkNaWUtcXGluc3RhcHBcXGFwcFxccGZwXFxkZWZhdWx0LmpwZyIsImNvbmZpcm1lZCI6dHJ1ZSwiaWF0IjoxNjg2NzQ1Mzg0LCJleHAiOjE2ODY3NDg5ODR9.bu0nSFOvxeyHc-HysVl4SpIPqAE0gvIrxp5bR89q86A

{
    "firstName": "Robert",
    "lastName": "Lewandowski"
}

### PATCH - pfp
POST http://localhost:3000/api/profile HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZmlyc3ROYW1lIjoiYmFydGVrIiwibGFzdE5hbWUiOiJrb3oiLCJlbWFpbCI6InVzZXJAdXNlciIsInBhc3N3b3JkIjoiJDJhJDA4JDU4YkM4blNhR1ZZRkd0ak51MjY4TnV2N1hueE5IZGlmbi9ORkdOa0toeFN0R3M3OTI1ZkZ5IiwicGZwIjoiRDpcXEJhcnRla1xcU3prb8WCYVxcxYHEhWN6bm_Fm8SHXFwwU1RFRkFOQ1pZS1xcaW5zdGFwcC1tYWluXFxhcHBcXHBmcFxcZGVmYXVsdC5qcGciLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjI1ODE2NCwiZXhwIjoxNjg2MjYxNzY0fQ._AumXeJWxpFHPNWPI_9ln7LDmZblxB_qyibxBJegdDU
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input2.jpg"
Content-Type: image/jpg

< ./input2.jpg

------FormBoundary1234

### GET - logout
GET http://localhost:3000/api/profile/logout HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZmlyc3ROYW1lIjoiSmFuMiIsImxhc3ROYW1lIjoiS293YTNsc2tpIiwiZW1haWwiOiJ1c2VyMTIzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA4JFNJNTVwdWZ4UzJUZmtkZmhieG5sb092VEtTcjZlSVEzT1JLTGh4SDQyczFvSDFKdjhmbExtIiwicGZwIjoiRDpcXEJhcnRla1xcU3prb8WCYVxcxYHEhWN6bm_Fm8SHXFwwU1RFRkFOQ1pZS1xcaW5zdGFwcC1tYWluXFxhcHBcXHBmcFxcZGVmYXVsdC5qcGciLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NTgxNDk1MSwiZXhwIjoxNjg1ODU4MTUxfQ.G98AfWR6AgkeAGyzNThIA39GpgBwzels0Zd5C0eK5us

### GET - pfp
GET http://localhost:3000/api/profile/pfp/0 HTTP/1.1
