### POST - register account
POST http://localhost:3000/api/user/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jan2",
    "lastName": "Kowa3lski",
    "email": "user123@gmail.com",
    "password": "QWERTY1234"
}

### GET - confirm account
GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZmlyc3ROYW1lIjoiSmFuMiIsImxhc3ROYW1lIjoiS293YTNsc2tpIiwiZW1haWwiOiJ1c2VyMTIzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDA4JGMwSXVZQjMwT0FDUTBTSEJ2dTFlNmVyeXlXWjlGNGgzQ0FXQ0dOMjFZSXg5L3pUdHZKSjR1IiwicGZwIjoiRDpcXEJhcnRla1xcU3prb8WCYVxcxYHEhWN6bm_Fm8SHXFwwU1RFRkFOQ1pZS1xcaW5zdGFwcC1tYWluXFxhcHBcXHBmcFxcZGVmYXVsdC5qcGciLCJjb25maXJtZWQiOmZhbHNlLCJpYXQiOjE2ODYyNTc4ODAsImV4cCI6MTY4NjI1NzkzMH0.Mc-tV_g8T-oYSltZ3lrJ0Dzy0FcG0-RoZwWzVbLYrxg
### GET - all users
GET http://localhost:3000/api/user HTTP/1.1

### POST - login
POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "user123@gmail.com",
    "password": "QWERTY1234"
}