### POST - register account
POST http://localhost:3000/api/user/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jan2",
    "lastName": "Kowa3lski",
    "email": "user12@gmail.com",
    "password": "QWERTY1234"
}

### GET - confirm account
GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZmlyc3ROYW1lIjoiSmFuIiwibGFzdE5hbWUiOiJLb3dhbHNraSIsImVtYWlsIjoidXNlcjJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMDgkc2FFWjFGVGVCUE5ERTlZRmExYmJ1LmI0OTUzclF2MEZXOTNxMzhuZXQ5cm5YOXBXMFFTMGEiLCJjb25maXJtZWQiOmZhbHNlLCJpYXQiOjE2ODUyMTMzNTAsImV4cCI6MTY4NTIxMzM4MH0.QfKFEwr4WC6K3RBFyVH2LcTL7CW_3Lrq3HeL-Bdas7k

### GET - all users
GET http://localhost:3000/api/user HTTP/1.1

### POST - login
POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "user2@gmail.com",
    "password": "QWERTY123"
}